// stackblitz/vue/tab-sync-example/src/app/ExampleView.vue
<script setup lang="ts">
import type { Subscription } from 'rxjs';
import { onMounted, onUnmounted, ref } from 'vue';
import {
  type Example,
  exampleState,
  exampleState$,
  replaceExamples,
  resetExamples
} from './example.cell';

/**
 * Sample datasets used to demonstrate state replacement and cross-tab sync.
 */
const samples: Example[][] = [
  [
    { id: 11, name: 'Luke', lastName: 'Skywalker' },
    { id: 38, name: 'Leia', lastName: 'Organa' },
    { id: 9, name: 'Han', lastName: 'Solo' }
  ],
  [
    { id: 22, name: 'Anakin', lastName: 'Skywalker' },
    { id: 44, name: 'Padmé', lastName: 'Amidala' },
    { id: 66, name: 'Obi-Wan', lastName: 'Kenobi' }
  ],
  [
    { id: 77, name: 'Din', lastName: 'Djarin' },
    { id: 88, name: 'Ahsoka', lastName: 'Tano' },
    { id: 99, name: 'Bo-Katan', lastName: 'Kryze' }
  ]
];

const snapshot = ref({
  value: exampleState.value,
  hasValue: exampleState.hasValue
});

const activeSample = ref<Example[]>(samples[0]);
const activeStateHint = ref('Initial value is [] (empty array)');
const displayActiveStateHint = ref(true);

let sub: Subscription;

onMounted(() => {
  sub = exampleState$.subscribe((emit) => {
    snapshot.value = {
      value: emit.snapshot.value,
      hasValue: emit.snapshot.hasValue
    };
  });
});

onUnmounted(() => {
  sub?.unsubscribe();
});

/**
 * Loads the active sample into the FeatureCell pipeline.
 *
 * When Tab Sync is enabled, the pipeline broadcasts the
 * finalized snapshot to all other tabs via BroadcastChannel.
 */
function loadSample(): void {
  displayActiveStateHint.value = false;
  activeStateHint.value = 'State updated and broadcast to all tabs.';
  replaceExamples(activeSample.value);
}

/** Resets the FeatureCell state to its initial value. */
function handleResetState(): void {
  resetExamples();
}

/** Updates the active sample when the dropdown selection changes. */
function handleSampleChange(event: Event): void {
  const index = Number((event.target as HTMLSelectElement).value);
  activeSample.value = samples[index];
}
</script>

<template>
  <div class="example-container">
    <div class="header">
      <div class="title">Vue - SDuX Vault Tab Sync Example</div>
      <div class="subtitle">
        This example demonstrates cross-tab state synchronization. Open this
        page in two browser tabs — updating state in one tab automatically
        propagates the change to the other via BroadcastChannel.
      </div>
    </div>

    <div class="section">
      <div class="label">Tab Sync Flow</div>
      <div class="flow-hint">Tab A → BroadcastChannel → Tab B</div>
    </div>

    <div class="section">
      <div class="state-container">
        <label class="label" for="sample-select">Sample Dataset</label>
        <div class="hint">
          Choose a character group to use as input state. Selecting a dataset
          updates the input preview — click Load &amp; Sync State to apply it.
        </div>
        <div class="hint">
          <select
            id="sample-select"
            class="sdux-select"
            @change="handleSampleChange">
            <option
              v-for="(sample, index) in samples"
              :key="index"
              :value="index"
              :selected="index === 0">
              {{ sample[0].name }} {{ sample[0].lastName }},
              {{ sample[1].name }} {{ sample[1].lastName }},
              {{ sample[2].name }} {{ sample[2].lastName }}
            </option>
          </select>
        </div>
      </div>
    </div>

    <div class="section column">
      <div class="state-container">
        <div class="label">Input State</div>
        <div class="hint">Data to replace and broadcast across tabs</div>
        <div class="hint file">
          <span class="emphasis">File:</span> app/ExampleView.vue
        </div>
        <textarea
          class="data-textarea"
          readonly
          :value="JSON.stringify(activeSample, null, 2)" />
      </div>

      <div class="state-container data-row">
        <div class="label">Synced FeatureCell State</div>
        <div class="hint">State synchronized across tabs</div>
        <div class="hint file">
          <span class="emphasis">File:</span> app/example.cell.ts
        </div>

        <template v-if="snapshot.hasValue">
          <textarea
            class="data-textarea"
            readonly
            :value="JSON.stringify(snapshot.value, null, 2)" />
          <div class="hint state">
            <span class="emphasis">State:</span> {{ activeStateHint }}
          </div>
          <div class="hint file">
            <template v-if="displayActiveStateHint">
              <span class="emphasis">File:</span> app/example.cell.ts
            </template>
            <template v-else>&nbsp;</template>
          </div>
        </template>

        <template v-else>
          <textarea class="data-textarea" readonly value=" " />
          <div class="hint state">
            <span class="emphasis">State:</span> cleared - pipeline has no
            active value for state.
          </div>
          <div class="hint file">
            <span class="emphasis">File:</span> app/example.cell.ts &nbsp;
          </div>
        </template>
      </div>
    </div>

    <div class="section">
      <div class="actions">
        <button type="button" class="sdux-button primary" @click="loadSample">
          Load &amp; Sync State
        </button>

        <div class="secondary-actions">
          <button type="button" class="sdux-button" @click="handleResetState">
            Reset State
          </button>
        </div>
      </div>
    </div>

    <div class="section learn-more">
      <div class="label">Learn More</div>
      <div class="learn-more-links">
        <a
          href="https://www.sdux-vault.com/docs/pipeline/behaviors/state"
          target="_blank"
          rel="noopener noreferrer"
          >State</a
        >
        <span class="separator">·</span>
        <a
          href="https://www.sdux-vault.com/docs/pipeline/behaviors/tab-sync"
          target="_blank"
          rel="noopener noreferrer"
          >Tab Sync</a
        >
        <span class="separator">·</span>
        <a
          href="https://www.sdux-vault.com/docs/pipeline/behaviors/state/updating"
          target="_blank"
          rel="noopener noreferrer"
          >Updating State</a
        >
        <span class="separator">·</span>
        <a
          href="https://www.sdux-vault.com/docs/pipeline/apis/feature-cell"
          target="_blank"
          rel="noopener noreferrer"
          >FeatureCell</a
        >
      </div>
    </div>
  </div>
</template>

<style scoped>
.example-container {
  display: flex;
  flex-direction: column;
  gap: 0.75rem;
  padding: 1rem;
}

.header {
  display: flex;
  flex-direction: column;
  gap: 0.25rem;
}

.title {
  font-size: 2rem;
  font-weight: 600;
  letter-spacing: 0.3px;
}

.subtitle {
  font-size: 1rem;
  color: #666;
  max-width: 600px;
}

.section {
  padding: 1rem;
}

.section.column {
  border: 1px solid rgba(0, 0, 0, 0.08);
  border-radius: 8px;
  display: flex;
  gap: 0.75rem;
}

@media (max-width: 768px) {
  .section.column {
    flex-direction: column;
  }

  .section.column .state-container {
    width: 100%;
  }
}

.state-container {
  flex: 1;
  display: flex;
  flex-direction: column;
  gap: 0.35rem;
  min-width: 0;
}

.state-container.data-row {
  height: 430px;
}

.textarea,
.data-textarea {
  width: 100%;
  box-sizing: border-box;
  height: 300px;
  padding: 0.5rem;
  border: 1px solid rgba(0, 0, 0, 0.08);
  border-radius: 6px;
  font-family: monospace;
  font-size: 0.8rem;
  background: #fafafa;
  color: #222;
}

.data-textarea.error {
  color: #d33;
}

.textarea {
  height: 175px;
}

.label {
  font-size: 1.1rem;
  font-weight: 600;
  text-transform: uppercase;
  letter-spacing: 0.5px;
  color: #666;
}

.flow-hint {
  margin-top: 0.25rem;
  font-size: 1rem;
  letter-spacing: 0.3px;
  color: #666;
}

.hint {
  font-size: 1rem;
  color: #777;
  margin-top: -0.15rem;
  margin-left: 0.5rem;
}

.hint.file {
  min-height: 16px;
  color: #999;
  font-family: monospace;
  font-size: 0.9rem;
}

.hint.state {
  margin-top: 0.15rem;
}

.emphasis {
  font-weight: 600;
  color: #555;
}

.actions {
  justify-content: flex-start;
  display: flex;
  align-items: center;
  gap: 3rem;
}

@media (max-width: 768px) {
  .actions {
    flex-direction: column;
    align-items: flex-start;
    gap: 2rem;
  }
}

.secondary-actions {
  display: flex;
  gap: 2rem;
}

@media (max-width: 768px) {
  .secondary-actions {
    gap: 1.5rem;
    flex-direction: column;
    align-items: flex-start;
  }
}

.status {
  height: 300px;
  font-size: 0.85rem;
  color: #666;
  display: flex;
  align-items: center;
  justify-content: center;
}

.learn-more {
  display: flex;
  flex-direction: column;
  gap: 0.35rem;
}

.learn-more-links {
  display: flex;
  align-items: center;
  gap: 0.75rem;
  font-size: 1rem;
}

.learn-more-links a {
  color: #555;
  text-decoration: none;
}

.learn-more-links a:hover {
  text-decoration: underline;
  color: #222;
}

.learn-more-links .separator {
  color: #ccc;
}
</style>

// stackblitz/react/tab-sync-example/src/app/ExampleView.tsx
import { ChangeEvent, useEffect, useState } from 'react';
import {
  Example,
  exampleState,
  exampleState$,
  initializeCell,
  replaceExamples,
  resetExamples
} from './example.cell';
import './ExampleView.css';

/**
 * Sample datasets used to demonstrate state replacement and cross-tab sync.
 */
const samples: Example[][] = [
  [
    { id: 11, name: 'Luke', lastName: 'Skywalker' },
    { id: 38, name: 'Leia', lastName: 'Organa' },
    { id: 9, name: 'Han', lastName: 'Solo' }
  ],
  [
    { id: 22, name: 'Anakin', lastName: 'Skywalker' },
    { id: 44, name: 'Padmé', lastName: 'Amidala' },
    { id: 66, name: 'Obi-Wan', lastName: 'Kenobi' }
  ],
  [
    { id: 77, name: 'Din', lastName: 'Djarin' },
    { id: 88, name: 'Ahsoka', lastName: 'Tano' },
    { id: 99, name: 'Bo-Katan', lastName: 'Kryze' }
  ]
];

/**
 * UI component for the Tab Sync example.
 *
 * This component consumes the Vault-backed state exposed by example.cell
 * and demonstrates cross-tab state synchronization. When state is updated
 * in one tab, the withTabSyncStateBehavior broadcasts the finalized snapshot
 * to other tabs via BroadcastChannel.
 *
 * The component does not manage state directly — it delegates all state
 * updates and lifecycle orchestration to the FeatureCell module.
 */
export function ExampleView() {
  const [snapshot, setSnapshot] = useState({
    value: exampleState.value,
    hasValue: exampleState.hasValue
  });
  const [activeSample, setActiveSample] = useState<Example[]>(samples[0]);
  const [activeStateHint, setActiveStateHint] = useState(
    'Initial value is [] (empty array)'
  );
  const [displayActiveStateHint, setDisplayActiveStateHint] = useState(true);

  /**
   * Subscribes to state emissions then initializes the FeatureCell.
   *
   * Initialization is deferred so the subscription is guaranteed to
   * be active before the Tab Sync controller begins BroadcastChannel
   * negotiation. This ensures the component catches the negotiation
   * snapshot that is committed synchronously via commitState.
   */
  useEffect(() => {
    const sub = exampleState$.subscribe((emit) => {
      setSnapshot({
        value: emit.snapshot.value,
        hasValue: emit.snapshot.hasValue
      });
    });
    initializeCell();
    return () => sub.unsubscribe();
  }, []);

  /**
   * Loads the active sample into the FeatureCell pipeline.
   *
   * When Tab Sync is enabled, the pipeline broadcasts the
   * finalized snapshot to all other tabs via BroadcastChannel.
   *
   * Architectural Flow:
   * Button Click
   *   → Component handler
   *   → Cell replaceState
   *   → Vault update
   *   → Pipeline execution
   *   → BroadcastChannel broadcast
   *   → Reactive UI refresh (all tabs)
   */
  function loadSample() {
    setDisplayActiveStateHint(false);
    setActiveStateHint('State updated and broadcast to all tabs.');
    replaceExamples(activeSample);
  }

  /** Resets the FeatureCell state to its initial value. */
  function handleResetState() {
    resetExamples();
  }

  /** Updates the active sample when the dropdown selection changes. */
  function handleSampleChange(event: ChangeEvent<HTMLSelectElement>) {
    const index = Number(event.target.value);
    setActiveSample(samples[index]);
  }

  return (
    <div className="example-container">
      <div className="header">
        <div className="title">React - SDuX Vault Tab Sync Example</div>
        <div className="subtitle">
          This example demonstrates cross-tab state synchronization. Open this
          page in two browser tabs — updating state in one tab automatically
          propagates the change to the other via BroadcastChannel.
        </div>
      </div>

      <div className="section">
        <div className="label">Tab Sync Flow</div>
        <div className="flow-hint">Tab A → BroadcastChannel → Tab B</div>
      </div>

      <div className="section">
        <div className="state-container">
          <label className="label" htmlFor="sample-select">
            Sample Dataset
          </label>
          <div className="hint">
            Choose a character group to use as input state. Selecting a dataset
            updates the input preview — click Load &amp; Sync State to apply it.
          </div>
          <div className="hint">
            <select
              id="sample-select"
              className="sdux-select"
              onChange={handleSampleChange}>
              {samples.map((sample, index) => (
                <option key={index} value={index}>
                  {sample[0].name} {sample[0].lastName}, {sample[1].name}{' '}
                  {sample[1].lastName}, {sample[2].name} {sample[2].lastName}
                </option>
              ))}
            </select>
          </div>
        </div>
      </div>

      <div className="section column">
        <div className="state-container">
          <div className="label">Input State</div>
          <div className="hint">Data to replace and broadcast across tabs</div>
          <div className="hint file">
            <span className="emphasis">File:</span> app/ExampleView.tsx
          </div>
          <textarea
            className="data-textarea"
            readOnly
            value={JSON.stringify(activeSample, null, 2)}
          />
        </div>

        <div className="state-container data-row">
          <div className="label">Synced FeatureCell State</div>
          <div className="hint">State synchronized across tabs</div>
          <div className="hint file">
            <span className="emphasis">File:</span> app/example.cell.ts
          </div>
          {snapshot.hasValue ? (
            <>
              <textarea
                className="data-textarea"
                readOnly
                value={JSON.stringify(snapshot.value, null, 2)}
              />
              <div className="hint state">
                <span className="emphasis">State:</span> {activeStateHint}
              </div>
              <div className="hint file">
                {displayActiveStateHint ? (
                  <>
                    <span className="emphasis">File:</span> app/example.cell.ts
                  </>
                ) : (
                  '\u00a0'
                )}
              </div>
            </>
          ) : (
            <>
              <textarea className="data-textarea" readOnly value=" " />
              <div className="hint state">
                <span className="emphasis">State:</span> cleared - pipeline has
                no active value for state.
              </div>
              <div className="hint file">
                <span className="emphasis">File:</span> app/example.cell.ts
                &nbsp;
              </div>
            </>
          )}
        </div>
      </div>

      <div className="section">
        <div className="actions">
          <button className="sdux-button primary" onClick={loadSample}>
            Load &amp; Sync State
          </button>

          <div className="secondary-actions">
            <button className="sdux-button" onClick={handleResetState}>
              Reset State
            </button>
          </div>
        </div>
      </div>

      <div className="section learn-more">
        <div className="label">Learn More</div>
        <div className="learn-more-links">
          <a
            href="https://www.sdux-vault.com/docs/pipeline/behaviors/state"
            target="_blank"
            rel="noopener noreferrer">
            State
          </a>
          <span className="separator">·</span>
          <a
            href="https://www.sdux-vault.com/docs/pipeline/behaviors/tab-sync"
            target="_blank"
            rel="noopener noreferrer">
            Tab Sync
          </a>
          <span className="separator">·</span>
          <a
            href="https://www.sdux-vault.com/docs/pipeline/behaviors/state/updating"
            target="_blank"
            rel="noopener noreferrer">
            Updating State
          </a>
          <span className="separator">·</span>
          <a
            href="https://www.sdux-vault.com/docs/pipeline/apis/feature-cell"
            target="_blank"
            rel="noopener noreferrer">
            FeatureCell
          </a>
        </div>
      </div>
    </div>
  );
}
