// stackblitz/svelte/basic-filter-reducer-example/src/app/ExampleView.svelte
<script lang="ts">
  import {
    type Example,
    exampleCell,
    replaceExamples,
    resetExamples,
    toggleError,
    toggleLoading
  } from './example.cell';

  const sample: Example[] = [
    { id: 11, name: 'Luke', lastName: 'Skywalker' },
    { id: 38, name: 'Leia', lastName: 'Organa' },
    { id: 9, name: 'Han', lastName: 'Solo' }
  ];

  let snapshot = $derived(exampleCell.state);

  let activeStateHint = $state('Initial value is [] (empty array)');
  let displayActiveStateHint = $state(true);
  let isLoading = $state(false);

  /** Loads sample data into the FeatureCell pipeline. */
  function loadSample(): void {
    displayActiveStateHint = false;
    activeStateHint =
      'State updated with sample data after filters and reducers run.';
    replaceExamples(sample);
  }

  /** Resets the FeatureCell state to its initial value. */
  function handleResetState(): void {
    resetExamples();
  }

  /** Toggles the loading flag on the current state. */
  function handleToggleLoading(): void {
    const next = !isLoading;
    isLoading = next;
    toggleLoading(next);
  }

  /** Toggles the error state between an Error instance and null. */
  function handleToggleError(): void {
    const hasError = snapshot.error !== null;
    const error = hasError ? null : new Error('Example error message');
    toggleError(error);
  }

  const filterCode = `[
  (examples: Example[]) => {

    return examples.filter(
      (example: Example) => example.name !== 'Han'
    );
  }
]`;

  const reducerCode = `[
  (examples: Example[]) => {
    return examples.map((example: Example) => {
      if (example.id === 11) {
        return { ...example, jedi: true };
      }
      return example;
    });
  }
]`;
</script>

<div class="example-container">
  <div class="header">
    <div class="title">Svelte - SDuX Vault Filter and Reducer Example</div>
    <div class="subtitle">
      This example shows how SDuX processes state through a pipeline: input data
      flows through filters and reducers before becoming the final FeatureCell
      state.
    </div>
  </div>

  <div class="section">
    <div class="label">FeatureCell Flow</div>
    <div class="flow-hint">Input → Filter → Reducer → Output</div>
  </div>

  <div class="section column">
    <div class="state-container">
      <div class="label">Filter</div>
      <div class="hint">
        Removes or blocks data before it enters the pipeline
      </div>
      <div class="hint file">
        <span class="emphasis">File:</span> app/example.cell.ts
      </div>
      <textarea class="textarea" readonly>{filterCode}</textarea>
    </div>

    <div class="state-container">
      <div class="label">Reducer</div>
      <div class="hint">Transforms each item in the state</div>
      <div class="hint file">
        <span class="emphasis">File:</span> app/example.cell.ts
      </div>
      <textarea class="textarea" readonly>{reducerCode}</textarea>
    </div>
  </div>

  <div class="section column">
    <div class="state-container">
      <div class="label">Input State</div>
      <div class="hint">Raw data before processing</div>
      <div class="hint file">
        <span class="emphasis">File:</span> app/ExampleView.svelte
      </div>
      <textarea class="data-textarea" readonly
        >{JSON.stringify(sample, null, 2)}</textarea>
    </div>

    <div class="state-container data-row">
      <div class="label">FeatureCell State</div>
      <div class="hint">Final state after filters and reducers run</div>
      <div class="hint file">
        <span class="emphasis">File:</span> app/example.cell.ts
      </div>

      {#if snapshot.isLoading}
        <div class="status">Loading...</div>
      {:else if snapshot.error}
        <textarea
          class="data-textarea error"
          readonly
          value={JSON.stringify(snapshot.error, null, 2)}></textarea>
        <div class="hint state">This is a VaultError display</div>
      {:else if snapshot.hasValue}
        <textarea
          class="data-textarea"
          readonly
          value={JSON.stringify(snapshot.value, null, 2)}></textarea>
        <div class="hint state">
          <span class="emphasis">State:</span>
          {activeStateHint}
        </div>
        <div class="hint file">
          {#if displayActiveStateHint}
            <span class="emphasis">File:</span> app/example.cell.ts
          {:else}
            &nbsp;
          {/if}
        </div>
      {:else}
        <textarea class="data-textarea" readonly value=" "></textarea>
        <div class="hint state">
          <span class="emphasis">State:</span> cleared - pipeline has no active value,
          error or loading status.
        </div>
        <div class="hint file">
          <span class="emphasis">File:</span> app/example.cell.ts &nbsp;
        </div>
      {/if}
    </div>
  </div>

  <div class="section">
    <div class="actions">
      <button type="button" class="sdux-button primary" onclick={loadSample}>
        Load Sample State
      </button>

      <div class="secondary-actions">
        <button type="button" class="sdux-button" onclick={handleResetState}>
          Reset State
        </button>
        <button type="button" class="sdux-button" onclick={handleToggleLoading}>
          Loading ({String(snapshot.isLoading)})
        </button>
        <button type="button" class="sdux-button" onclick={handleToggleError}>
          Error ({String(snapshot.error !== null)})
        </button>
      </div>
    </div>
  </div>

  <div class="section learn-more">
    <div class="label">Learn More</div>
    <div class="learn-more-links">
      <a
        href="https://www.sdux-vault.com/docs/pipeline/behaviors/filters"
        target="_blank"
        rel="noopener noreferrer">Filters</a>
      <span class="separator">·</span>
      <a
        href="https://www.sdux-vault.com/docs/pipeline/behaviors/reducers"
        target="_blank"
        rel="noopener noreferrer">Reducers</a>
      <span class="separator">·</span>
      <a
        href="https://www.sdux-vault.com/docs/pipeline/apis/feature-cell"
        target="_blank"
        rel="noopener noreferrer">FeatureCell</a>
    </div>
  </div>
</div>

<style>
  .example-container {
    display: flex;
    flex-direction: column;
    gap: 0.75rem;
    padding: 1rem;
  }

  .header {
    display: flex;
    flex-direction: column;
    gap: 0.25rem;
  }

  .title {
    font-size: 2rem;
    font-weight: 600;
    letter-spacing: 0.3px;
  }

  .subtitle {
    font-size: 1rem;
    color: #666;
    max-width: 600px;
  }

  .section {
    padding: 1rem;
  }

  .section.column {
    border: 1px solid rgba(0, 0, 0, 0.08);
    border-radius: 8px;
    display: flex;
    gap: 0.75rem;
  }

  @media (max-width: 768px) {
    .section.column {
      flex-direction: column;
    }

    .section.column .state-container {
      width: 100%;
    }
  }

  .state-container {
    flex: 1;
    display: flex;
    flex-direction: column;
    gap: 0.35rem;
    min-width: 0;
  }

  .state-container.data-row {
    height: 430px;
  }

  .textarea,
  .data-textarea {
    width: 100%;
    box-sizing: border-box;
    height: 300px;
    padding: 0.5rem;
    border: 1px solid rgba(0, 0, 0, 0.08);
    border-radius: 6px;
    font-family: monospace;
    font-size: 0.8rem;
    background: #fafafa;
    color: #222;
  }

  .data-textarea.error {
    color: #d33;
  }

  .textarea {
    height: 175px;
  }

  .label {
    font-size: 1.1rem;
    font-weight: 600;
    text-transform: uppercase;
    letter-spacing: 0.5px;
    color: #666;
  }

  .flow-hint {
    margin-top: 0.25rem;
    font-size: 1rem;
    letter-spacing: 0.3px;
    color: #666;
  }

  .hint {
    font-size: 1rem;
    color: #777;
    margin-top: -0.15rem;
    margin-left: 0.5rem;
  }

  .hint.file {
    min-height: 16px;
    color: #999;
    font-family: monospace;
    font-size: 0.9rem;
  }

  .hint.state {
    margin-top: 0.15rem;
  }

  .emphasis {
    font-weight: 600;
    color: #555;
  }

  .actions {
    justify-content: flex-start;
    display: flex;
    align-items: center;
    gap: 3rem;
  }

  @media (max-width: 768px) {
    .actions {
      flex-direction: column;
      align-items: flex-start;
      gap: 2rem;
    }
  }

  .secondary-actions {
    display: flex;
    gap: 2rem;
  }

  @media (max-width: 768px) {
    .secondary-actions {
      gap: 1.5rem;
      flex-direction: column;
      align-items: flex-start;
    }
  }

  .status {
    height: 300px;
    font-size: 0.85rem;
    color: #666;
    display: flex;
    align-items: center;
    justify-content: center;
  }

  .learn-more {
    display: flex;
    flex-direction: column;
    gap: 0.35rem;
  }

  .learn-more-links {
    display: flex;
    align-items: center;
    gap: 0.75rem;
    font-size: 1rem;
  }

  .learn-more-links a {
    color: #555;
    text-decoration: none;
  }

  .learn-more-links a:hover {
    text-decoration: underline;
    color: #222;
  }

  .learn-more-links .separator {
    color: #ccc;
  }
</style>

// stackblitz/vue/basic-filter-reducer-example/src/app/ExampleView.vue
<script setup lang="ts">
import { ref } from 'vue';
import {
  type Example,
  exampleCell,
  replaceExamples,
  resetExamples,
  toggleError,
  toggleLoading
} from './example.cell';

const sample: Example[] = [
  { id: 11, name: 'Luke', lastName: 'Skywalker' },
  { id: 38, name: 'Leia', lastName: 'Organa' },
  { id: 9, name: 'Han', lastName: 'Solo' }
];

const snapshot = exampleCell.useReactiveState();

const activeStateHint = ref('Initial value is [] (empty array)');
const displayActiveStateHint = ref(true);
const isLoading = ref(false);

/** Loads sample data into the FeatureCell pipeline. */
function loadSample(): void {
  displayActiveStateHint.value = false;
  activeStateHint.value =
    'State updated with sample data after filters and reducers run.';
  replaceExamples(sample);
}

/** Resets the FeatureCell state to its initial value. */
function handleResetState(): void {
  resetExamples();
}

/** Toggles the loading flag on the current state. */
function handleToggleLoading(): void {
  const next = !isLoading.value;
  isLoading.value = next;
  toggleLoading(next);
}

/** Toggles the error state between an Error instance and null. */
function handleToggleError(): void {
  const hasError = snapshot.error !== null;
  const error = hasError ? null : new Error('Example error message');
  toggleError(error);
}
</script>

<template>
  <div class="example-container">
    <div class="header">
      <div class="title">Vue - SDuX Vault Filter and Reducer Example</div>
      <div class="subtitle">
        This example shows how SDuX processes state through a pipeline: input
        data flows through filters and reducers before becoming the final
        FeatureCell state.
      </div>
    </div>

    <div class="section">
      <div class="label">FeatureCell Flow</div>
      <div class="flow-hint">Input → Filter → Reducer → Output</div>
    </div>

    <div class="section column">
      <div class="state-container">
        <div class="label">Filter</div>
        <div class="hint">
          Removes or blocks data before it enters the pipeline
        </div>
        <div class="hint file">
          <span class="emphasis">File:</span> app/example.cell.ts
        </div>
        <textarea class="textarea" readonly>
[
  (examples: Example[]) => {

    return examples.filter(
      (example: Example) => example.name !== 'Han'
    );
  }
]</textarea>
      </div>

      <div class="state-container">
        <div class="label">Reducer</div>
        <div class="hint">Transforms each item in the state</div>
        <div class="hint file">
          <span class="emphasis">File:</span> app/example.cell.ts
        </div>
        <textarea class="textarea" readonly>
[
  (examples: Example[]) => {
    return examples.map((example: Example) => {
      if (example.id === 11) {
        return { ...example, jedi: true };
      }
      return example;
    });
  }
]</textarea>
      </div>
    </div>

    <div class="section column">
      <div class="state-container">
        <div class="label">Input State</div>
        <div class="hint">Raw data before processing</div>
        <div class="hint file">
          <span class="emphasis">File:</span> app/ExampleView.vue
        </div>
        <textarea
          class="data-textarea"
          readonly
          :value="JSON.stringify(sample, null, 2)" />
      </div>

      <div class="state-container data-row">
        <div class="label">FeatureCell State</div>
        <div class="hint">Final state after filters and reducers run</div>
        <div class="hint file">
          <span class="emphasis">File:</span> app/example.cell.ts
        </div>

        <template v-if="snapshot.isLoading">
          <div class="status">Loading...</div>
        </template>

        <template v-else-if="snapshot.error">
          <textarea
            class="data-textarea error"
            readonly
            :value="JSON.stringify(snapshot.error, null, 2)" />
          <div class="hint state">This is a VaultError display</div>
        </template>

        <template v-else-if="snapshot.hasValue">
          <textarea
            class="data-textarea"
            readonly
            :value="JSON.stringify(snapshot.value, null, 2)" />
          <div class="hint state">
            <span class="emphasis">State:</span> {{ activeStateHint }}
          </div>
          <div class="hint file">
            <template v-if="displayActiveStateHint">
              <span class="emphasis">File:</span> app/example.cell.ts
            </template>
            <template v-else>&nbsp;</template>
          </div>
        </template>

        <template v-else>
          <textarea class="data-textarea" readonly value=" " />
          <div class="hint state">
            <span class="emphasis">State:</span> cleared - pipeline has no
            active value, error or loading status.
          </div>
          <div class="hint file">
            <span class="emphasis">File:</span> app/example.cell.ts &nbsp;
          </div>
        </template>
      </div>
    </div>

    <div class="section">
      <div class="actions">
        <button type="button" class="sdux-button primary" @click="loadSample">
          Load Sample State
        </button>

        <div class="secondary-actions">
          <button type="button" class="sdux-button" @click="handleResetState">
            Reset State
          </button>
          <button
            type="button"
            class="sdux-button"
            @click="handleToggleLoading">
            Loading ({{ String(snapshot.isLoading) }})
          </button>
          <button type="button" class="sdux-button" @click="handleToggleError">
            Error ({{ String(snapshot.error !== null) }})
          </button>
        </div>
      </div>
    </div>

    <div class="section learn-more">
      <div class="label">Learn More</div>
      <div class="learn-more-links">
        <a
          href="https://www.sdux-vault.com/docs/pipeline/behaviors/filters"
          target="_blank"
          rel="noopener noreferrer"
          >Filters</a
        >
        <span class="separator">·</span>
        <a
          href="https://www.sdux-vault.com/docs/pipeline/behaviors/reducers"
          target="_blank"
          rel="noopener noreferrer"
          >Reducers</a
        >
        <span class="separator">·</span>
        <a
          href="https://www.sdux-vault.com/docs/pipeline/apis/feature-cell"
          target="_blank"
          rel="noopener noreferrer"
          >FeatureCell</a
        >
      </div>
    </div>
  </div>
</template>

<style scoped>
.example-container {
  display: flex;
  flex-direction: column;
  gap: 0.75rem;
  padding: 1rem;
}

.header {
  display: flex;
  flex-direction: column;
  gap: 0.25rem;
}

.title {
  font-size: 2rem;
  font-weight: 600;
  letter-spacing: 0.3px;
}

.subtitle {
  font-size: 1rem;
  color: #666;
  max-width: 600px;
}

.section {
  padding: 1rem;
}

.section.column {
  border: 1px solid rgba(0, 0, 0, 0.08);
  border-radius: 8px;
  display: flex;
  gap: 0.75rem;
}

@media (max-width: 768px) {
  .section.column {
    flex-direction: column;
  }

  .section.column .state-container {
    width: 100%;
  }
}

.state-container {
  flex: 1;
  display: flex;
  flex-direction: column;
  gap: 0.35rem;
  min-width: 0;
}

.state-container.data-row {
  height: 430px;
}

.textarea,
.data-textarea {
  width: 100%;
  box-sizing: border-box;
  height: 300px;
  padding: 0.5rem;
  border: 1px solid rgba(0, 0, 0, 0.08);
  border-radius: 6px;
  font-family: monospace;
  font-size: 0.8rem;
  background: #fafafa;
  color: #222;
}

.data-textarea.error {
  color: #d33;
}

.textarea {
  height: 175px;
}

.label {
  font-size: 1.1rem;
  font-weight: 600;
  text-transform: uppercase;
  letter-spacing: 0.5px;
  color: #666;
}

.flow-hint {
  margin-top: 0.25rem;
  font-size: 1rem;
  letter-spacing: 0.3px;
  color: #666;
}

.hint {
  font-size: 1rem;
  color: #777;
  margin-top: -0.15rem;
  margin-left: 0.5rem;
}

.hint.file {
  min-height: 16px;
  color: #999;
  font-family: monospace;
  font-size: 0.9rem;
}

.hint.state {
  margin-top: 0.15rem;
}

.emphasis {
  font-weight: 600;
  color: #555;
}

.actions {
  justify-content: flex-start;
  display: flex;
  align-items: center;
  gap: 3rem;
}

@media (max-width: 768px) {
  .actions {
    flex-direction: column;
    align-items: flex-start;
    gap: 2rem;
  }
}

.secondary-actions {
  display: flex;
  gap: 2rem;
}

@media (max-width: 768px) {
  .secondary-actions {
    gap: 1.5rem;
    flex-direction: column;
    align-items: flex-start;
  }
}

.status {
  height: 300px;
  font-size: 0.85rem;
  color: #666;
  display: flex;
  align-items: center;
  justify-content: center;
}

.learn-more {
  display: flex;
  flex-direction: column;
  gap: 0.35rem;
}

.learn-more-links {
  display: flex;
  align-items: center;
  gap: 0.75rem;
  font-size: 1rem;
}

.learn-more-links a {
  color: #555;
  text-decoration: none;
}

.learn-more-links a:hover {
  text-decoration: underline;
  color: #222;
}

.learn-more-links .separator {
  color: #ccc;
}
</style>
